import './globals.css';
import type { Metadata } from 'next';
import { inter } from './fonts';
import ClientOnly from './components/ClientOnly';
import Footer from './components/Sections/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${inter.className}
          bg-gradient-to-br from-indigo-950 from-% via-black 3xl:via-40% via-30% to-black to-90% sm:bg-black
          pb-10 sm:pb-0 mx-auto max-w-2xl md:max-w-4xl lg:max-w-7xl px-6 lg:px-8 h-screen bg-fixed
        `}
      >
        <ClientOnly>{children}</ClientOnly>
        <Footer />
      </body>
    </html>
  );
}
