import './globals.css';
import type { Metadata } from 'next';
import { inter } from './fonts';
import ClientOnly from './components/ClientOnly';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>{children}</ClientOnly>
      </body>
    </html>
  );
}
